services:
  db:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    restart: always
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    build: api
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  # Flutter service
  app:
    build: app
    ports:
      - 5000:5000