name: mediaplex
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.5
  lottie: ^2.5.0
  provider: ^6.0.5
  equatable: ^2.0.5
  flutter_svg: ^2.0.7
  flutter_bloc: ^8.1.3
  google_fonts: ^4.0.4
  english_words: ^4.0.0
  cupertino_icons: ^1.0.2
  lecle_yoyo_player: ^0.0.6
  flutter_screenutil: ^5.8.4
  shared_preferences: ^2.2.0
  # curved_navigation_bar: ^1.0.3
  uicons_regular_rounded: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/images/icons/
    - assets/images/categories/

  fonts:
    - family: Mukta
      fonts:
        - asset: assets/fonts/Mukta-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Mukta-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mukta-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Mukta-Regular.ttf
          weight: 500
        - asset: assets/fonts/Mukta-Medium.ttf
          weight: 400
        - asset: assets/fonts/Mukta-Light.ttf
          weight: 300
        - asset: assets\fonts\Mukta-ExtraLight.ttf
          weight: 200